version: "3"
services:

  backend:
    build: ./ADjangoProject
    volumes:
      - ./ADjangoProject:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./coffeelocator
    volumes:
      - ./coffeelocator:/app/build
    ports:
      - "3000:3000"
    depends_on:
      - backend



