# Generated by Django 3.2.19 on 2024-04-26 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoffeeVendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='coffeevendor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coffeevendor',
            name='vendor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CoffeeVendors.vendortype'),
        ),
    ]
